version: "3.9"
services:
  frpc:
    container_name: frpc
    image: fatedier/frpc:v0.48.0
    restart: unless-stopped
    command: --config /etc/frp/frpc.ini
    network_mode: host
    volumes:
      - ./frpc.ini:/etc/frp/frpc.ini
