version: "3.9"
services:
  frpc:
    container_name: frpc
    image: fatedier/frpc:v0.53.2
    restart: unless-stopped
    command: --config /etc/frp/frpc.toml
    network_mode: host
    volumes:
      - ./frpc.toml:/etc/frp/frpc.toml
      - /tmp/files:/tmp/files
