version: "3.9"
services:
  frps:
    container_name: frps
    image: fatedier/frps:v0.53.2
    restart: unless-stopped
    command: --config /etc/frp/frps.ini
    ports:
      - "7000:7000/tcp"
      - "7000:7000/udp"
      - "7500:7500"
    volumes:
      - ./frps.ini:/etc/frp/frps.ini
