# frpc.toml
[common]
server_addr = k8s.shubhamtatvamasi.com
server_port = 7000

[web]
type = http
local_port = 80
custom_domains = k8s.shubhamtatvamasi.com

[proxmox]
type = https
local_ip = 192.168.1.101
local_port = 8006
custom_domains = k8s.shubhamtatvamasi.com

[kubernetes]
type = https
local_ip = 192.168.1.111
local_port = 6443
subdomain = cluster

[ssh_k8s]
type = tcp
local_ip = 192.168.1.101
local_port = 22
remote_port = 22

[ssh]
type = tcp
local_ip = 192.168.1.111
local_port = 22
remote_port = 2222

[static_files]
type = tcp
remote_port = 3000
plugin = static_file
plugin_local_path = /tmp/files

[rancher]
type = https
local_ip = rancher.cattle-system.svc.cluster.local
local_port = 443
subdomain = rancher

[kubernetes_api]
type = https
local_ip = kubernetes.default.svc.cluster.local
local_port = 443
subdomain = kubernetes
