apiVersion: v1
kind: Service
metadata:
  labels:
    app: frps
  name: frps
spec:
  type: LoadBalancer
  selector:
    app: frps
  ports:
  - name: bind-port
    port: 7000
    protocol: TCP
    targetPort: 7000
  - name: dashboard-port
    port: 7500
    protocol: TCP
    targetPort: 7500
  - name: vhost-http-port
    port: 80
    protocol: TCP
    targetPort: 80
  - name: vhost-https-port
    port: 443
    protocol: TCP
    targetPort: 443
