apiVersion: v1
kind: ConfigMap
metadata:
  name: frpc-config
  namespace: caddy-system
data:
  frpc.ini: |
    [common]
    server_addr = k8s.shubhamtatvamasi.com
    server_port = 7000

    [caddy_http]
    type = http
    local_ip = caddy-ingress-controller
    local_port = 80
    custom_domains = nginx.k8s.shubhamtatvamasi.com

    [caddy_https]
    type = https
    local_ip = caddy-ingress-controller
    local_port = 443
    custom_domains = nginx.k8s.shubhamtatvamasi.com
