apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frpc
  name: frpc
  namespace: caddy-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frpc
  template:
    metadata:
      labels:
        app: frpc
    spec:
      containers:
      - image: fatedier/frpc:v0.53.2
        name: frpc
        command: ["/usr/bin/frpc", "--config", "/etc/frp/frpc.toml"]
        volumeMounts:
        - name: frpc-volume
          subPath: frpc.toml
          mountPath: /etc/frp/frpc.toml
      volumes:
      - name: frpc-volume
        configMap:
          name: frpc-config
