apiVersion: v1
kind: ConfigMap
metadata:
  name: frpc-config
data:
  frpc.toml: |
    [common]
    server_addr = k8s.shubhamtatvamasi.com
    server_port = 7000

    [web]
    type = http
    local_ip = nginx
    local_port = 80
    subdomain = nginx
