---
- name: Copy frps config file
  template:
    src: frps.ini.j2
    dest: "/etc/frp/frps.ini"

- name: Copy frps service file
  template:
    src: frps.service.j2
    dest: "/etc/systemd/system/frps.service"

- name: Enable service frps
  service:
    name: frps
    enabled: yes

- name: Restart service frps
  service:
    name: frps
    state: restarted
