---
- name: Remove frpc config file
  file:
    state: absent
    path: /etc/frp/frpc.toml

- name: Copy frps config file
  template:
    src: frps.toml.j2
    dest: "/etc/frp/frps.toml"

- name: Copy frps service file
  template:
    src: frps.service.j2
    dest: "/etc/systemd/system/frps.service"

- name: Enable service frps
  service:
    name: frps
    enabled: yes

- name: Restart service frps
  service:
    name: frps
    state: restarted
